# Generated by Django 2.0 on 2017-12-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Start', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='email',
            field=models.EmailField(default='rgardishyan@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
