# Generated by Django 2.0 on 2017-12-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_task_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
