# Generated by Django 2.0 on 2017-12-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0004_auto_20171222_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Task'),
        ),
    ]
