# Generated by Django 2.0 on 2017-12-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0006_completedtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtask',
            name='inprogress',
            field=models.BooleanField(default=False),
        ),
    ]
