# Generated by Django 2.0 on 2018-01-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0007_completedtask_inprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedtask',
            name='inprogress',
        ),
        migrations.AddField(
            model_name='task',
            name='inprogress',
            field=models.BooleanField(default=False),
        ),
    ]
