# Generated by Django 2.0 on 2018-01-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0008_auto_20180103_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedtask',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Task'),
        ),
    ]
