# Generated by Django 2.0 on 2017-12-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthDate', models.DateField()),
                ('rang', models.CharField(max_length=50)),
                ('secretKey', models.CharField(max_length=5, verbose_name='Secret Key')),
            ],
        ),
    ]
