# Generated by Django 2.0 on 2017-12-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('People', '0002_people_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
