# Generated by Django 2.0 on 2018-01-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('People', '0003_people_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='activation',
            field=models.CharField(default=12345, max_length=15),
            preserve_default=False,
        ),
    ]
