# Generated by Django 2.0 on 2017-12-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='slug',
            field=models.CharField(default='file', max_length=100),
            preserve_default=False,
        ),
    ]
