# Generated by Django 2.0 on 2017-12-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Logs', '0002_auto_20171223_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
